// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmSMAK543Y_J5QPqt77eODT9XvJY4jT0',
    appId: '1:752768577463:web:6d7fff029a85c84ae10232',
    messagingSenderId: '752768577463',
    projectId: 'todolist-9efcb',
    authDomain: 'todolist-9efcb.firebaseapp.com',
    storageBucket: 'todolist-9efcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxkqdEQz1odJXOH-3k87-SmPLLm3xKsIE',
    appId: '1:752768577463:ios:c3a1120069517bfde10232',
    messagingSenderId: '752768577463',
    projectId: 'todolist-9efcb',
    storageBucket: 'todolist-9efcb.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxkqdEQz1odJXOH-3k87-SmPLLm3xKsIE',
    appId: '1:752768577463:ios:c3a1120069517bfde10232',
    messagingSenderId: '752768577463',
    projectId: 'todolist-9efcb',
    storageBucket: 'todolist-9efcb.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYmSMAK543Y_J5QPqt77eODT9XvJY4jT0',
    appId: '1:752768577463:web:433b91f655f7bfcde10232',
    messagingSenderId: '752768577463',
    projectId: 'todolist-9efcb',
    authDomain: 'todolist-9efcb.firebaseapp.com',
    storageBucket: 'todolist-9efcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBykS-mMGKrAm0G5Uhtsqm-bk5fAt7-to',
    appId: '1:752768577463:android:63bb17fa22f55e5ce10232',
    messagingSenderId: '752768577463',
    projectId: 'todolist-9efcb',
    storageBucket: 'todolist-9efcb.firebasestorage.app',
  );

}